spring.datasource.url=jdbc:postgresql://crossover.proxy.rlwy.net:50260/railway
spring.datasource.username=postgres
spring.datasource.password=DUtxOOVolCNECOVGZoPxbjKeeJdhjCDr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}